/*
 * Interview Tests Mock API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.SiteInfoDevices;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * Information on a site
 */
@Schema(description = "Information on a site")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2023-03-12T19:38:32.340663737Z[GMT]")
public class SiteInfo {
  @SerializedName("id")
  private String id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("devices")
  private List<SiteInfoDevices> devices = new ArrayList<SiteInfoDevices>();

  public SiteInfo id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the site
   * @return id
  **/
  @Schema(example = "pear-tree", required = true, description = "The ID of the site")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public SiteInfo name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The display name of the site
   * @return name
  **/
  @Schema(example = "Pear Tree", required = true, description = "The display name of the site")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public SiteInfo devices(List<SiteInfoDevices> devices) {
    this.devices = devices;
    return this;
  }

  public SiteInfo addDevicesItem(SiteInfoDevices devicesItem) {
    this.devices.add(devicesItem);
    return this;
  }

   /**
   * Get devices
   * @return devices
  **/
  @Schema(required = true, description = "")
  public List<SiteInfoDevices> getDevices() {
    return devices;
  }

  public void setDevices(List<SiteInfoDevices> devices) {
    this.devices = devices;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SiteInfo siteInfo = (SiteInfo) o;
    return Objects.equals(this.id, siteInfo.id) &&
        Objects.equals(this.name, siteInfo.name) &&
        Objects.equals(this.devices, siteInfo.devices);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, devices);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SiteInfo {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    devices: ").append(toIndentedString(devices)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
